### ISSUE TITLE
Two parallel Hamamatsu cameras

### ISSUE THREAD

**Issue by EAAeby** [langmo/youscope#10]
Hello!
This is more to your information than something else, as this setup wont be kept on the long run. 
We are currently using YouScope2 on our Windows 7 computer to control our Nikon Te-2000 microscope. We have two Hamamatsu camera connected to the computer:
- Hamamatsu C9100 EM-CCD
- Hamamatsu C13440-20CU CMOS

Restarting YouScope after the installation, the microscope configuration directly assigned all old parameters to the new camera, completely ignoring the old one. I tried my best, however I wasn't able to connect both cameras in parallel.

Is this a known issue? From our side, no need for a fix (if it is really a problem), I just wanted to inform you.

Best, 
EAAeby

**Comment by langmo** [comment]
Hi,
I don't completely get what is the intended behavior, and what YouScope does instead. Can you maybe send me the configuration file together with a description which property should be set for which camera?
Best,
Moritz

**Comment by EAAeby** [comment]
Hi Moritz, 
My apologies. I don't have the configuration file anymore. 
We were testing a new hamamatsu camera and wanted to compare both pictures. Therefore, we had both cameras connected to the microscope and to the computer. YouScope would then only recognize the new hamamatsu camera. I guess, because both were "sharing" the same device adapter. 
In contrast, when there was the old hamamatsu camera and an andor camera plugged, YouScope properly recognized both and gave us the possibility to choose between both. 
I hope this helps. Sorry again. 
Best, 
Elise

**Comment by cunyap** [comment]
Hi Elise,

I can confirm that YouScope 2018 works with two or more Hammamatsu cameras attached. If you are using the new Hamamatsu C13440-20CU CMOS you need to activate the compatibility mode in its driver such that you can use it along with the older ones. I'll attach a screenshot for illustration once I'm back in the lab.

I hope this solves your issue.

Best,
Andreas

**Comment by EAAeby** [comment]
Hi Andreas, 
I wasn't aware of this feature, thank you for the information and solving it! My mistake.
Best, and thanks again!
Elise
