### ISSUE TITLE
Why I receive error when I try to add microscope camera ?

### ISSUE THREAD

**Issue by fsb-ivan** [langmo/youscope#11]
Hello,

I hope you can help us about Youscope. We have Olympus gx51 microscope with Olympus DP25 microscope camera. 

Unfortunately  we get error

see screenshot: http://prntscr.com/l6ln8e

it says: 

Tue Oct 16 09:14:51 CEST 2018:
Could not add device driver.
Details:
MicroscopeDriverException: Could not initilize driver. Check if device is correctly connected, or retry with different pre-initialization settings.
Exception: Error in device "TwainCam": TwainDevice Image acquisition sequence fails: [Size] Image transfer failed: 5 source never signaled 'Transfer Ready' (waited 10000.3 ms)  (34)

what should we do to enable it ?

please reply

Thank you

Have a nice day

**Comment by langmo** [comment]
Hi,
it seems that you try to use the TWAIN driver to connect to the camera. In some sense, this treats the camera as a scanner; to be more precise: not only the YouScope driver treats the camera as some kind of scanner, the complete Windows operating system, including all graphics programs, should treat the camera as a scanner device (at least if everything is installed and working correctly).
This has the advantage that can run an initial test to better locate the problem. Specifically, just open whatever graphics program with which you can get an image from a scanner, for example MS Paint. Now, try to get an image from the camera using this graphics program. Does it work?

**Comment by langmo** [comment]
no reply from original poster
