### ISSUE TITLE
Windows 10?

### ISSUE THREAD

**Issue by dschrein** [langmo/youscope#9]
hi! the other users of our microscope want to switch to Windows 10. has youScope been tested there?

thanks

**Comment by langmo** [comment]
YouScope runs on Win10. However, if there might be problems for your specific hardware/driver configuration is not foreseeable. 

In general, I would never make a non-reversible hardware switch, independently if I use YouScope or any other microscope control software. It's not even only the specific control software, there might be other problems completely independent of which software you use. You never know what might happen. Personally, I would use the opportunity to completely replace the current computer with a newer one (microscope computers are typically rather old). Then, install and test the new one with Win10. While doing so, you can then always quickly switch back to the old configuration. This is especially recommendable if you cannot block the microscope for a week or so, but always have to let people measure their stuff while you set up the new system (which usually takes some time).
An alternative to a new computer is of course to simply add a second partition to the old one and run Win10 and Win7 in parallel.

I hope this answers the question: YouScope runs on Win10, but if everything works out fine for your specific setup is another question.
